[package]
name = "RTasks"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
serde = {version = "1.0.203", features = ["derive"]}
serde_derive = "1.0.203"
aes-gcm = "0.10.3"
hex = "0.4.3"
rand = "0.8.5"
sha2 = "0.10.8"